# Generated by Django 5.2.4 on 2025-07-24 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskparticipant",
            options={
                "verbose_name": "Участник задачи",
                "verbose_name_plural": "Участники задачи",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="task",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_delegated",
            field=models.BooleanField(default=False, verbose_name="Делегировано"),
        ),
        migrations.AlterField(
            model_name="task",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный",
            ),
        ),
        migrations.AlterField(
            model_name="taskmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AlterField(
            model_name="taskmessage",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="tasks.task",
                verbose_name="Задача",
            ),
        ),
        migrations.AlterField(
            model_name="taskmessage",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время"),
        ),
        migrations.AlterField(
            model_name="taskparticipant",
            name="role",
            field=models.CharField(
                choices=[
                    ("executor", "Исполнитель"),
                    ("responsible", "Ответственный"),
                    ("observer", "Наблюдатель"),
                ],
                max_length=20,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="taskparticipant",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="tasks.task",
                verbose_name="Задача",
            ),
        ),
        migrations.AlterField(
            model_name="taskparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
