# Generated by Django 5.1.7 on 2025-09-06 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_task_file_taskfile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="delegated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата делегирования"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="delegated_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delegated_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Делегировано от",
            ),
        ),
    ]
